# Generated by Django 2.2.5 on 2019-10-11 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(default=uuid.uuid4, max_length=1000, unique=True)),
                ('name', models.CharField(default='', max_length=300)),
                ('description', models.TextField(default='Description here', max_length=999)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
