# Generated by Django 2.2.5 on 2019-10-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FooApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
