# Generated by Django 2.2.5 on 2019-10-11 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FooApp', '0003_auto_20191011_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
