# Generated by Django 2.2.5 on 2019-10-11 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FooApp', '0004_auto_20191011_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.CharField(default=uuid.uuid4, max_length=999, unique=True),
        ),
    ]
